First playable version
Nemo11235/CS160-Final-Project pull request #21
Opened 2022-03-04 08:53 UTC by jawes123

2022-03-04 18:02 UTC, Nemo11235 requested changes

2022-03-04 19:01 UTC, jawes123 commented on wordle.js
> +
Sounds good! Will do.

2022-03-04 19:23 UTC, merged

2022-03-04 19:27 UTC, Nemo11235 reviewed
looks good, approved

2022-03-14 23:40 UTC, jawes123 commented
Case 1: the program runs correctly on terminal
Case 2: hard-coded, playable game follows all rules of "Wordle"